### ISSUE TITLE
Retire to Attic?

### ISSUE THREAD

**Issue by apetro** [uPortal-Attic/ContentManagementPortlet#2]
Last commit in 2012.

Anyone using this? Anyone using this enough that anyone's going to maintain it? No? Should update the README etc. to indicate abandonware, move the repo to [the Attic](https://github.com/uPortal-Attic) and [mark it archived](https://help.github.com/articles/archiving-repositories/) or so?

**Comment by ChristianMurphy** [comment]
I'd lean toward moving it to the attic

**Comment by drewwills** [comment]
:+1: -- we should do those things.

**Comment by apetro** [comment]
Transferred.

**Comment by apetro** [comment]
Updated README to reflect that in attic. Bumping to "Archived" state next.
